### ISSUE TITLE
How do we save and retrieve answers?

### ISSUE THREAD

**Issue by humblecoder** [FissionHQ/vue-survey-builder#3]
Would you mind providing an example that captures data from the `QuestionsView`?

**Comment by rajeshwarpatlolla** [comment]
`QuestionsView` is a read only component, to which we pass list of questions to render.
If you see [this line](https://github.com/rajeshwarpatlolla/vue-survey-builder-test/blob/master/src/components/QuestionsView.vue#L88), we are getting questions from props. Here in your methods if you access `this. questions` then you will get the list of questions.
The list is passed from another component in [this line](https://github.com/rajeshwarpatlolla/vue-survey-builder-test/blob/master/src/components/TestSurveyBuilder.vue#L5). `TestSurveyBuilder.vue` is your main page, where we are using survey builder and questions view components. You can even get the updated questions list [from this line](https://github.com/rajeshwarpatlolla/vue-survey-builder-test/blob/master/src/components/TestSurveyBuilder.vue#L44) in the example.
