### ISSUE TITLE
Text field should be extended to can add more fields

### ISSUE THREAD

**Issue by lgt** [FissionHQ/vue-survey-builder#4]
Hi, thanks for this component how could I extended the component to be able to add more fields on TEXT option?

https://github.com/FissionHQ/vue-survey-builder/blob/master/src/SurveyBuilder.vue#L102

**Comment by rajeshwarpatlolla** [comment]
You can fork this repo and make changes in the source, in the line which you mentioned above to add more types, if you would like to have your own custom type of input fields.
